FROM public.ecr.aws/docker/library/node:hydrogen-bookworm-slim
ENV NODE_ENV development
WORKDIR /src
COPY package.json /src/
COPY package-lock.json /src/
COPY . /src/
RUN npm i
CMD ["npm", "run", "dev"]