services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=toolkit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "psql", "-U", "postgres", "toolkit"]
      interval: 1s
      timeout: 5s
      retries: 5
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    command: >
      sh -c "python manage.py migrate --noinput --settings=toolkit.settings_docker_dev &&
             python manage.py runserver --settings=toolkit.settings_docker_dev 0.0.0.0:8000"
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=toolkit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy