services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JOBS_DB_HOST=${JOBS_DB_HOST}
      - JOBS_DB_USER=${JOBS_DB_USER}
      - JOBS_DB_PORT=${JOBS_DB_PORT}
      - JOBS_DB_DB_NAME=${JOBS_DB_DB_NAME}
      - JOBS_DB_PASSWORD=${JOBS_DB_PASSWORD}
      - CONFIG_PATH=${CONFIG_PATH}
    ports:
      - "7432:5432"
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    command: >
      sh -c "python manage.py migrate --noinput --settings=toolkit.settings_production &&
             python manage.py runserver --settings=toolkit.settings_production 0.0.0.0:8090"
    volumes:
      - .:/src
      - ./config:/config
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        mode: non-blocking
        tag: backend
    ports:
      - "8090:8080"
      